// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oblivion.Data.Db;

#nullable disable

namespace Oblivion.Data.Migrations
{
    [DbContext(typeof(OblivionDbContext))]
    [Migration("20260108095935_ManyToManyFiles")]
    partial class ManyToManyFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("AnalyzedFileWorkspace", b =>
                {
                    b.Property<Guid>("FilesID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspacesID")
                        .HasColumnType("TEXT");

                    b.HasKey("FilesID", "WorkspacesID");

                    b.HasIndex("WorkspacesID");

                    b.ToTable("AnalyzedFileWorkspace");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.AnalyzedFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnalized")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Sha256");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.FileModificationNotes", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalyzedFileID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AnalyzedFileID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.Workspace", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("AnalyzedFileWorkspace", b =>
                {
                    b.HasOne("Oblivion.Data.Entities.AnalyzedFile", null)
                        .WithMany()
                        .HasForeignKey("FilesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oblivion.Data.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspacesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oblivion.Data.Entities.FileModificationNotes", b =>
                {
                    b.HasOne("Oblivion.Data.Entities.AnalyzedFile", "AnalyzedFile")
                        .WithMany("Notes")
                        .HasForeignKey("AnalyzedFileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalyzedFile");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.AnalyzedFile", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
