// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oblivion.Data.Db;

#nullable disable

namespace Oblivion.Data.Migrations
{
    [DbContext(typeof(OblivionDbContext))]
    [Migration("20260106143413_AddNameFieldToFile")]
    partial class AddNameFieldToFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Oblivion.Data.Entities.AnalyzedFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Sha256");

                    b.HasIndex("WorkspaceID");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.FileModificationNotes", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalyzedFileID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AnalyzedFileID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.Workspace", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOpenedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.AnalyzedFile", b =>
                {
                    b.HasOne("Oblivion.Data.Entities.Workspace", "Workspace")
                        .WithMany("Files")
                        .HasForeignKey("WorkspaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.FileModificationNotes", b =>
                {
                    b.HasOne("Oblivion.Data.Entities.AnalyzedFile", "AnalyzedFile")
                        .WithMany("Notes")
                        .HasForeignKey("AnalyzedFileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalyzedFile");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.AnalyzedFile", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Oblivion.Data.Entities.Workspace", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
